# Custom Language File for Launcher Customizer

[ejs.app]
title = "Leet Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/wildsneaker/LeetLauncher"
mediaGiftURL = "https://youtu.be/wz5IA30Lng4?si=tzOjHz3i-dgYcoGw"
mediaDiscordURL = "https://discord.com/channels/673859724055150602/1299406627098591313"

[ejs.settings]
sourceGithubLink = "https://github.com/wildsneaker/LeetLauncher"
supportLink = "https://github.com/wildsneaker/LeetLauncher/issues"

[ejs.welcome]
welcomeHeader = "WE1COM3 T0 1EE7 CAMUN17Y"
welcomeDescription = "Всего лишь лаунчер для нашего локального камьюнити,"
welcomeDescCTA = "хз что тут писать."
