# Custom Language File for Launcher Customizer

[ejs.app]
title = "Leet Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/wildsneaker/LeetLauncher"
mediaGiftURL = "https://www.youtube.com/watch?v=E4WlUXrJgy4"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/LeetLauncher"
supportLink = "https://github.com/dscalZi/LeetLauncher/issues"

[ejs.welcome]
welcomeHeader = "WE1COM3 T0 1EE7 CAMUN17Y"
welcomeDescription = "Всего лишь лаунчер для нашего локального камьюнити,"
welcomeDescCTA = "хз что тут писать."
